---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev{{ teamid }}-villain-prod
  namespace: rhdh-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab-gitlab.{{ ocpdomain }}/dev{{ teamid }}/villain-gitops.git
    targetRevision: HEAD
    path: ./helm/app
    helm:
      parameters:
      - name: namespace.name
        value: dev{{ teamid }}-workshop-prod
      - name: environment
        value: prod
      - name: image.tag
        value: prod-v1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: dev{{ teamid }}-workshop-prod
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name|test(".-dockercfg-."))'
      kind: ServiceAccount
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: -1
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 2m # the maximum amount of time allowed for the backoff strategy